DROP TABLE IF EXISTS images;

CREATE TABLE images(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    folder_id INTEGER NOT NULL,
    url VARCHAR(511) NOT NULL,
    name VARCHAR(255),
    description TEXT
);
